import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className="header">
        <div className="nav-box">
          <nav>
            <ul className="menu-bar">
              <li>
                <Link href="/login">
                  <a>Login</a>
                </Link>
              </li>
              <li>
                <Link href="/register">
                  <a>Register</a>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>

      <main>
        <h1>
          Welcome to Cobra!
        </h1>

        <p>
          Your new private bank
        </p>

        {/* Ajouter une Image */}
      </main>
    </div>
  )
}

export default Home
