import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import pic from '../styles/me-pousse-G.png'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center mt-[10%] text-6xl font-bold">
          Welcome to Cobra!
        </h1>

        <p className="text-center text-xl font-medium mt-5">
          Your new private bank
        </p>

        <div className="flex justify-center mt-[5%]">
        <Image
          alt="welcome logo"
          src={pic}
          width={500}
          height={500}
        /> 
        </div>     
      </main>
    </div>
  )
}

export default Home
